### ISSUE TITLE
Move to official org?

### ISSUE THREAD

**Issue by zenorocha** [dracula/slate-dracula#3]
Hey @sean-hill 👋  

I'm the creator of Dracula color scheme. I was searching for themes created by the community and I found yours. Good job by the way!

I was wondering if you are interested in transferring this repository to the official organization (https://github.com/dracula). You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the site (https://draculatheme.com).

What do you think?

**Comment by sean-hill** [comment]
@zenorocha definitely! Let me know if you need anything from me 😀

**Comment by zenorocha** [comment]
Great! I just sent you an invite to join the organization.

Once you accept it, you'll be able to transfer the repo and I'll take care of adding it to the site.

Thanks for building this! 🎉

**Comment by sean-hill** [comment]
Awesome! I just accepted the invite.

**Comment by zenorocha** [comment]
You can now navigate to your repo, click on Settings, and then follow the steps in the Transfer section.

**Comment by sean-hill** [comment]
@zenorocha like this?

![image](https://user-images.githubusercontent.com/1205866/105063277-caadfa80-5a38-11eb-8ff4-c07fee2a2ac1.png)
